### ISSUE TITLE
NoMethodError: undefined method `assert_warning'

### ISSUE THREAD

**Issue by pelbyl** [ruby/date#106]
https://github.com/ruby/date/blob/c2d9cc29280e0eabb0bc72175c80704f1737a9fb/test/date/test_date_strftime.rb#L195

Probably it's better to rewrite this test without assert_warning since it's not defined.

**Comment by jeremyevans** [comment]
This is part of `test-unit-ruby-core`, which is in the Gemfile.  Did you follow the steps at https://github.com/ruby/date?tab=readme-ov-file#development ?

**Comment by pelbyl** [comment]
Yes, I have`test-unit-ruby-core-1.0.6`  gem installed.

**Comment by jeremyevans** [comment]
Can you post the output of `bundle exec rake test` ?
