### ISSUE TITLE
[Feature] Add Kernel#Date when require 'date'

### ISSUE THREAD

**Issue by americodls** [ruby/date#24]
Reference to: https://bugs.ruby-lang.org/issues/17022

What if we have a method `Kernel#Date` that delegates to `Date.parse` or `Date.iso8601` ?

Dates could be written more naturally, right?

```ruby
Date("2020-01-13") - Date("2019-01-13")
```
Capitalized methods are defined on the Kernel module to facilitate construction of basic types:

```ruby
Kernel.methods.grep(/^[A-Z].*/)
#=> [:Rational, :Complex, :URI, :Integer, :Float, :String, :Array, :Hash, :Pathname]
```

The method `BigDecimal` is added when the corresponding library is required:

```ruby
require 'bigdecimal'
Kernel.methods.grep(/^[A-Z].*/)
#=> [:Rational, :Complex, :BigDecimal, :URI, :Integer, :Float, :String, :Array, :Hash, :Pathname]
```

The proposal is to do the same for `Date`, when we do `require 'date'`, a method `Kernel#Date` would be added.

**Comment by jeremyevans** [comment]
I'm against this.  I don't want more libraries adding `Kernel` methods for every class.  `Date.new` and `DateTime.new` work fine for Date/DateTime construction and can be used, and they are more efficient than trying to parse a string.   For string parsing, it's best to use dedicated methods, such as `iso8601`.
