### ISSUE TITLE
[BUG] Compiler Error 'RUBY_TYPED_FROZEN_SHAREABLE' undeclared here

### ISSUE THREAD

**Issue by nicobayati** [ruby/date#28]
Hello,
currently i cant update some gems, because i get this error:

date_core.c:2980:57: error: 'RUBY_TYPED_FROZEN_SHAREABLE' undeclared here (not in a function)
 2980 |     RUBY_TYPED_FREE_IMMEDIATELY|RUBY_TYPED_WB_PROTECTED|RUBY_TYPED_FROZEN_SHAREABLE,
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:245: date_core.o] Error 1

I update as user, not as root.
Complete output from "LANG=C gem update --debug --verbose --backtrace 2>&1 | tee output.txt"
[output.txt](https://github.com/ruby/date/files/5733758/output.txt)

**Comment by hsbt** [comment]
Thanks.  @mrkn was fixed this and I released date-3.1.1. 

Can you try with date-3.1.1?

**Comment by XhmikosR** [comment]
Confirmed it works now.

BTW since CI was failing, 3.1.0 shouldn't have been released in the first place.

**Comment by nicobayati** [comment]
Thank you for this incredibly quick response. The program compiles correctly for me.
