### ISSUE TITLE
build failed with ruby 2.6.7

### ISSUE THREAD

**Issue by akiotajima** [ruby/date#83]
According to https://rubygems.org/gems/date, 'date' supported ruby version was >=2.4.
However date_core.c refers RB_WARN_CATEGORY_DEPRECATED introduced by Ruby 3.
I wonder if you could check RB_WARN_* in the build process or #Ifndef or anything.
Thanks.

**Comment by hsbt** [comment]
Thanks. It's wrong required version of gemspec. We only test with Ruby 2.7+. I update gemspec and test versions at #84.

I'm not sure there is strong reason to remove Ruby 2.6 now. I add it to them.
