### ISSUE TITLE
DateTime object not comparable with ActiveSupport::TimeWithZone?

### ISSUE THREAD

**Issue by ssoulless** [ruby/date#95]
This expectation started to fail after I installed this gem v.3.3.3
```ruby
# order.purchased_at = Sun, 26 Jan 0020 00:00:00 UTC +00:00
# order.purchased_at.class == ActiveSupport::TimeWithZone
expect(order.purchased_at).to eq 'Sun, 26 Jan 0020 00:00:00 UTC +00:00'.to_datetime
```

If I remove this gem the expectation passes

**Comment by jeremyevans** [comment]
The `date` library does not define String#to_datetime.  You should probably report this to the ActiveSupport maintainers.  If you think this is a bug in `date` itself, please post a self contained example that does not use ActiveSupport.
